#! /usr/bin/python3

import argparse
import json
import os
import sys

#   Constants

FILENAME = '.gitignore'
DEFAULT_KEY = 'DEFAULT'
DEFAULT_VALUES = [
    '*.swp'
]
EDITOR = 'vim'

#   ============================================================
#   Class definition
#   ============================================================

class GitignoreFile:
    """
    Represents a .gitignore file
    """

    def __init__(self, options):
        """
        Constructor
        """
        self.list = options.list
        self.replace = options.replace
        self.edit = options.edit
        self.quiet = options.quiet

        # Load .gitignorerc if it exists, else create it

        self.typelist = load_defaults()

        if not options.type:
            self.type = DEFAULT_KEY
            if DEFAULT_KEY not in self.typelist:
                self.typelist[DEFAULT_KEY] = DEFAULT_VALUES
        else:
            if options.type not in self.typelist:
                types = ["'" + type + "'" for type in self.typelist]
                typelist = ", ".join(types)
                p = typelist.rfind(',')
                if p > -1:
                    typelist = typelist[0:p] + ", or " + typelist[p + 2:]
                raise ValueError(f'If specified, type must be one of {typelist}')
            self.type = options.type


    def create(self):
        """
        Creates the .gitignore file
        """
        if not self.quiet:
            print('Creating new {}'.format(FILENAME))

        with open(FILENAME, 'wt') as f:
            for line in self.typelist[self.type]:
                f.write(line + '\n')

    def main(self):

        #   List the file if requested

        if self.list:
            if exists():
                list_file()
            else:
                print('No {} file exists'.format(FILENAME))
            sys.exit(0)

        #   Create the file if it does not exist,
        #   or if exists and the replace option was specified

        if exists():
            if self.replace:
                self.create()
            else:
                if not self.quiet:
                    print('Not replacing existing {}'.format(FILENAME))
                    print('Use -r flag to replace')
                    print('Try -h for help')
        else:
            self.create()

        #   List the contents of the file

        if not self.quiet and not self.edit:
            list_file()

        #   Bring it up in an editor if the edit option was specified

        if self.edit:
            edit_file()


def load_defaults(write_file=True):
    filename = os.path.expanduser("~/.gitignorerc")
    if os.path.exists(filename):
        with open(filename, "rt") as fp:
            defaults = json.load(fp)
    else:
        defaults = {
            'py': ['*.swp', '*.pyc', '*.pyo', '__pycache__', '.idea/', 'venv/'],
            'ly': ['*.swp', '*.mid', '*.midi', '*.ogg'],
            'java': ['*.swp', 'build/', 'doc/', '*.class', '.classpath', '.project'],
        }
        if write_file:
            with open(filename, "wt") as fp:
                json.dump(defaults, fp, indent=2, sort_keys=True)
    return defaults


def list_file():
    """
    Lists the file
    """
    with open(FILENAME) as f:
        for line in f:
            line = line.strip()
            print(line)


def edit_file():
    """
    Invokes an editor on the file
    """
    os.system('{} {}'.format(EDITOR, FILENAME))


def exists():
    """
    Returns True if the .gitignore file exists
    """
    return os.path.exists(FILENAME)


#   ============================================================
#   Mainline
#   ============================================================

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Creates a basic {} file in the current directory'.format(FILENAME))
    parser.add_argument('-l', '--list',
                        help='Lists the current {}'.format(FILENAME),
                        action='store_true')
    parser.add_argument('-r', '--replace',
                        help='Replaces the current {}, if it exists'.format(FILENAME),
                        action='store_true')
    parser.add_argument('-q', '--quiet',
                        help='Suppresses the printing of the {} file'.format(FILENAME),
                        action='store_true')
    parser.add_argument('-e', '--edit',
                        action='store_true',
                        help='Edit the file when done')
    typelist = load_defaults(write_file=False)
    parser.add_argument('type', nargs='?',
                        help=f'Type of files ({[name for name in typelist]})'
                        )
    options = parser.parse_args()
    gfile = GitignoreFile(options)
    gfile.main()
