editor: vim
filetypes:
  java:
    - "*.swp"
    - build/
    - doc/
    - "*.class"
    - .classpath
    - .project
    - ".vscode/"
  go:
    - "*.swp"
    - ".vscode/"
  py:
    - "*.swp"
    - "*.pyc"
    - "*.pyo"
    - ".vscode/"
    - __pycache__
    - .idea/
    - venv/
    - build/
    - dist/
    - "*.egg-info/"
  ly:
    - "*.swp"
    - "*.mid"
    - "*.ogg"
