editor: vim
filetypes:
  java:
    - "*.swp"
    - ".vscode/"
    - "*.class"
    - "*.log"
    - "*.jar"
    - "*.war"
    - "*.ear"
    - "target/"
    - "build/"
    - "bin/"
    - ".gradle/"
    - ".settings/"
    - ".classpath"
    - ".project"
    - "out/"
  go:
    - "*.swp"
    - ".vscode/"
    - "bin/"
    - "vendor/"
    - "*.test"
    - "*.out"
    - "go.work"
    - "go.work.sum"
    - ".exe"
    - ".dll"
    - ".so"
    - ".dylib"
  py:
    - "*.swp"
    - "*.pyc"
    - "__pycache__/"
    - ".vscode/"
    - ".venv/"
    - "venv/"
    - "env/"
    - ".env"
    - "build/"
    - "dist/"
    - "*.egg-info/"
    - ".pytest_cache/"
    - ".mypy_cache/"
    - ".ipynb_checkpoints/"
  rust:
    - "*.swp"
    - ".vscode/"
    - "target/"
    - "**/*.rs.bk"
    - "debug/"
    - "release/"
    - "*.pdb"
  c:
    - "*.swp"
    - ".vscode/"
    - "*.o"
    - "*.obj"
    - "*.out"
    - "*.a"
    - "*.lib"
    - "*.so"
    - "*.dylib"
    - "*.exe"
    - "dist/"
    - "build/"
    - "*.gch"
    - "*.pch"
  cpp:
    - "*.swp"
    - ".vscode/"
    - "*.o"
    - "*.obj"
    - "*.out"
    - "*.a"
    - "*.lib"
    - "*.so"
    - "*.dylib"
    - "*.exe"
    - "dist/"
    - "build/"
    - "*.gch"
    - "*.pch"
    - "*.idb"
    - "*.pdb"
    - "*.tlog"
    - "*.lastbuildstate"
    - "ipch/"
    - "*.VC.db"
    - "*.VC.opendb"